question_data = [
    {"category": "Science: Computers",
     "type": "multiple", "difficulty": "easy",
     "question": "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
     "correct_answer": "Apple",
     "incorrect_answers": ["Microsoft", "Atari", "Commodore"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which internet company began life as an online bookstore called &#039;Cadabra&#039;?",
     "correct_answer": "Amazon",
     "incorrect_answers": ["eBay", "Overstock", "Shopify"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "When Gmail first launched, how much storage did it provide for your email?",
     "correct_answer": "1GB", "incorrect_answers": ["512MB", "5GB", "Unlimited"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.",
     "correct_answer": "Binary", "incorrect_answers": ["JavaScript", "C++", "Python"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What was the name given to Android 4.3?",
     "correct_answer": "Jelly Bean",
     "incorrect_answers": ["Lollipop", "Nutella", "Froyo"]},
    {"category": "Science: Computers",
     "type": "boolean", "difficulty": "medium",
     "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form"
                 ". ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
     "correct_answer": "JavaScript", "incorrect_answers": ["C#", "Python", "PHP"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these people was NOT a founder of Apple Inc?",
     "correct_answer": "Jonathan Ive",
     "incorrect_answers": ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How many values can a single byte represent?",
     "correct_answer": "256", "incorrect_answers": ["8", "1", "1024"]}
]
